//! Launch command lines and home folders for bot terminals.
//!
//! Each bot runs its agent's own interface in its home folder, by default
//! `<state>/bots/<bot id>`. The home holds a generated `AGENTS.md` with the
//! coordinator prompt, so every agent that reads project instructions learns
//! its role. Agents that support it also get the Harness Harlot tools on the
//! command line.
use std::fs::{self, OpenOptions};
use std::io::{ErrorKind, Read as _, Write as _};
use std::os::unix::fs::OpenOptionsExt as _;
use std::path::{Path, PathBuf};
use std::thread;
use std::time::Duration;

use anyhow::{Context, Result, bail};
use hh_protocol::{BotSpec, CodingAgent, TerminalProfile};
use uuid::Uuid;

use super::threads::{prepare_threads_directory, valid_session_id};

const COORDINATOR_PROMPT: &str = include_str!("../../bundled/bot-prompt.md");
const OMP_EXTENSION: &[u8] = include_bytes!("../../bundled/hh-omp.ts");
const OMP_EXTENSION_FILE: &str = "hh-omp.ts";
const CONTEXT_FILE: &str = "AGENTS.md";
/// First line of every generated `AGENTS.md`; a file without it belongs to
/// the user and is never overwritten.
const CONTEXT_MARKER: &str = "<!-- Generated by Harness Harlot for bot ";
const MCP_SERVER_NAME: &str = "harness-harlot";
const MAX_BUNDLED_FILE_BYTES: u64 = 1024 * 1024;
/// Sweeps of a deleted bot's home, and the pause before each, while its
/// exiting agents may still write into it.
const HOME_REMOVAL_SWEEPS: u32 = 20;
const HOME_REMOVAL_DELAY: Duration = Duration::from_millis(250);

/// The bot identity a launch command is built for.
pub(crate) struct BotLaunch<'a> {
    pub(crate) bot_id: Uuid,
    pub(crate) name: &'a str,
    pub(crate) project_dir: Option<&'a str>,
    pub(crate) spec: &'a BotSpec,
    /// Saved agent session to resume; only omp bots have threads.
    pub(crate) resume: Option<&'a str>,
}

/// A prepared bot launch: the command line to type and the folder its shell
/// starts in.
pub(crate) struct PreparedLaunch {
    pub(crate) command: String,
    pub(crate) home: PathBuf,
    /// False when a custom home already holds the user's own `AGENTS.md`,
    /// which is left untouched.
    pub(crate) context_written: bool,
}

/// Directory holding shared bot launch files and default bot homes:
/// `<state>/bots`.
pub(crate) fn bots_directory(state_dir: &Path) -> PathBuf {
    state_dir.join("bots")
}

/// The folder a bot's shell starts in: its custom home, or the owner-only
/// default `<state>/bots/<bot id>`, created on demand.
pub(crate) fn bot_home(bots_dir: &Path, bot_id: Uuid, spec: &BotSpec) -> Result<PathBuf> {
    if let Some(home) = spec.home.as_deref() {
        let home = PathBuf::from(home);
        if !crate::process::valid_local_cwd(&home) {
            bail!("bot home {} is not an existing directory", home.display());
        }
        return Ok(home);
    }
    prepare_directory(bots_dir)?;
    let home = default_bot_home(bots_dir, bot_id);
    prepare_directory(&home)?;
    Ok(home)
}

fn default_bot_home(bots_dir: &Path, bot_id: Uuid) -> PathBuf {
    bots_dir.join(bot_id.to_string())
}

/// Prepares the bot's home and its `AGENTS.md`, writes the extension and MCP
/// files the command references, and builds the shell command line that
/// starts the agent. `hh_cli` is the `hh` executable serving the Harness
/// Harlot MCP tools.
pub(crate) fn prepare_launch(
    bot: &BotLaunch<'_>,
    agents: &[CodingAgent],
    bots_dir: &Path,
    hh_cli: Option<&Path>,
) -> Result<PreparedLaunch> {
    let agent = bot.spec.agent;
    if matches!(agent, TerminalProfile::Terminal | TerminalProfile::Tmux) {
        bail!("{} is not a coding agent", agent.display_name());
    }
    let executable = agents
        .iter()
        .find(|candidate| candidate.profile == agent)
        .with_context(|| format!("{} is not installed", agent.display_name()))?;
    let home = bot_home(bots_dir, bot.bot_id, bot.spec)?;
    let context_written = write_context_file(bot, &home)?;
    prepare_directory(bots_dir)?;
    let mut argv = vec![executable.path.clone()];
    match agent {
        TerminalProfile::Omp => {
            let extension = bots_dir.join(OMP_EXTENSION_FILE);
            write_if_changed(&extension, OMP_EXTENSION)?;
            argv.extend(["-e".to_owned(), utf8_path(&extension)?]);
            let threads = prepare_threads_directory(bots_dir, bot.bot_id)?;
            argv.extend(["--session-dir".to_owned(), utf8_path(&threads)?]);
            if let Some(session) = bot.resume {
                if !valid_session_id(session) {
                    bail!("invalid thread id {session:?}");
                }
                argv.extend(["--resume".to_owned(), session.to_owned()]);
            }
        }
        TerminalProfile::Claude => {
            if let Some(hh_cli) = hh_cli {
                let config = bots_dir.join(format!("{}.mcp.json", bot.bot_id));
                let json = serde_json::json!({
                    "mcpServers": {
                        MCP_SERVER_NAME: { "command": utf8_path(hh_cli)?, "args": ["mcp"] }
                    }
                });
                let bytes = serde_json::to_vec(&json).context("encode bot MCP config")?;
                write_if_changed(&config, &bytes)?;
                argv.extend(["--mcp-config".to_owned(), utf8_path(&config)?]);
            }
        }
        TerminalProfile::Codex => {
            if let Some(hh_cli) = hh_cli {
                argv.extend([
                    "-c".to_owned(),
                    format!(
                        "mcp_servers.{MCP_SERVER_NAME}.command={}",
                        toml_string(&utf8_path(hh_cli)?)?
                    ),
                    "-c".to_owned(),
                    format!("mcp_servers.{MCP_SERVER_NAME}.args=[\"mcp\"]"),
                ]);
            }
        }
        _ => {}
    }
    let command = argv
        .iter()
        .map(|argument| shell_quote(argument))
        .collect::<Vec<_>>()
        .join(" ");
    Ok(PreparedLaunch {
        command,
        home,
        context_written,
    })
}

/// Removes a deleted bot's launch files and its default home folder, without
/// following a symlink in its place. A custom home is never touched. Failures
/// are logged, never fatal.
pub(crate) fn remove_bot_files(bots_dir: &Path, bot_id: Uuid) {
    let home = default_bot_home(bots_dir, bot_id);
    let first = remove_home(&home);
    // The bot's agents were just told to exit and may still flush session
    // files into the home, recreating it; keep sweeping off the caller's
    // thread until they are done.
    let sweep = thread::Builder::new()
        .name("hh-bot-home-removal".to_owned())
        .spawn(move || {
            let mut result = first;
            for _ in 0..HOME_REMOVAL_SWEEPS {
                thread::sleep(HOME_REMOVAL_DELAY);
                result = remove_home(&home);
            }
            if let Err(error) = result {
                eprintln!("failed to remove bot home {}: {error}", home.display());
            }
        });
    if let Err(error) = sweep {
        eprintln!("could not keep removing a bot home: {error}");
    }
    // `prompt.md` files were written by earlier versions.
    for suffix in ["mcp.json", "prompt.md"] {
        let _ = fs::remove_file(bots_dir.join(format!("{bot_id}.{suffix}")));
    }
}

fn remove_home(home: &Path) -> std::io::Result<()> {
    match fs::symlink_metadata(home) {
        Ok(metadata) if metadata.is_dir() => fs::remove_dir_all(home),
        Ok(_) => fs::remove_file(home),
        Err(error) if error.kind() == ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error),
    }
}

/// Writes the bot's `AGENTS.md` into `home`. A default home always gets it;
/// in a custom home an existing file without the generated marker is the
/// user's and stays untouched, which returns false.
fn write_context_file(bot: &BotLaunch<'_>, home: &Path) -> Result<bool> {
    let path = home.join(CONTEXT_FILE);
    let bytes = context_file(bot);
    if bot.spec.home.is_none() {
        hh_protocol::atomic_write_private(&path, bytes.as_bytes())
            .with_context(|| format!("write {}", path.display()))?;
        return Ok(true);
    }
    if !context_file_replaceable(&path)? {
        return Ok(false);
    }
    write_replacing(&path, bytes.as_bytes())
        .with_context(|| format!("write {}", path.display()))?;
    Ok(true)
}

/// Whether `path` is absent or a regular file Harness Harlot generated.
/// Symlinks are never followed and count as the user's.
fn context_file_replaceable(path: &Path) -> Result<bool> {
    let file = match OpenOptions::new()
        .read(true)
        .custom_flags(libc::O_NOFOLLOW | libc::O_CLOEXEC | libc::O_NONBLOCK)
        .open(path)
    {
        Ok(file) => file,
        Err(error) if error.kind() == ErrorKind::NotFound => return Ok(true),
        Err(error) if error.raw_os_error() == Some(libc::ELOOP) => return Ok(false),
        Err(error) => return Err(error).with_context(|| format!("read {}", path.display())),
    };
    if !file.metadata()?.is_file() {
        return Ok(false);
    }
    let mut head = Vec::with_capacity(CONTEXT_MARKER.len());
    file.take(CONTEXT_MARKER.len() as u64)
        .read_to_end(&mut head)
        .with_context(|| format!("read {}", path.display()))?;
    Ok(head == CONTEXT_MARKER.as_bytes())
}

/// Atomically replaces `path` with an owner-only file, in a directory that
/// belongs to the user and keeps its own permissions.
fn write_replacing(path: &Path, bytes: &[u8]) -> std::io::Result<()> {
    let parent = path.parent().unwrap_or(Path::new("/"));
    let temporary = parent.join(format!(".{CONTEXT_FILE}.{}.tmp", Uuid::new_v4()));
    let written = (|| {
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(&temporary)?;
        file.write_all(bytes)?;
        file.sync_all()?;
        fs::rename(&temporary, path)
    })();
    if written.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    written
}

/// The bot's `AGENTS.md`: the marker, the coordinator prompt, and the bot's
/// identity, project folder and standing instructions.
fn context_file(bot: &BotLaunch<'_>) -> String {
    let mut prompt = format!(
        "{CONTEXT_MARKER}{}; rewritten on every launch. -->\n",
        bot.bot_id
    );
    prompt.push_str(COORDINATOR_PROMPT.trim_end());
    prompt.push_str("\n\n## Your identity\nYour name is \"");
    prompt.push_str(bot.name);
    prompt.push_str("\". The user may address you by it.\n");
    if let Some(project_dir) = bot.project_dir {
        prompt.push_str("Your project folder: ");
        prompt.push_str(project_dir);
        prompt.push_str(". Workers you open go there by default.\n");
    }
    if let Some(instructions) = bot.spec.instructions.as_deref() {
        prompt.push_str("\n## Standing instructions from the user\n");
        prompt.push_str(instructions.trim());
        prompt.push('\n');
    }
    prompt
}

fn prepare_directory(directory: &Path) -> Result<()> {
    hh_protocol::ensure_private_directory(directory)
        .with_context(|| format!("prepare bot directory {}", directory.display()))
}

fn write_if_changed(path: &Path, bytes: &[u8]) -> Result<()> {
    let unchanged = match hh_protocol::read_private_file(path, MAX_BUNDLED_FILE_BYTES) {
        Ok(existing) => existing == bytes,
        Err(error) if error.kind() == ErrorKind::NotFound => false,
        Err(error) => return Err(error).with_context(|| format!("read {}", path.display())),
    };
    if !unchanged {
        hh_protocol::atomic_write_private(path, bytes)
            .with_context(|| format!("write {}", path.display()))?;
    }
    Ok(())
}

fn utf8_path(path: &Path) -> Result<String> {
    path.to_str()
        .map(str::to_owned)
        .with_context(|| format!("path is not UTF-8: {}", path.display()))
}

/// A TOML basic string: JSON string escaping is a subset of TOML's.
fn toml_string(value: &str) -> Result<String> {
    serde_json::to_string(value).context("encode TOML string")
}

/// POSIX single-quoting, left bare when every byte is shell-safe. The
/// `'\''` escape also works in fish.
fn shell_quote(value: &str) -> String {
    let safe = !value.is_empty()
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || b"@%+=:,./-_".contains(&byte));
    if safe {
        value.to_owned()
    } else {
        format!("'{}'", value.replace('\'', "'\\''"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn agents() -> Vec<CodingAgent> {
        [
            (TerminalProfile::Omp, "/opt/bin/omp"),
            (TerminalProfile::Claude, "/opt/bin/claude"),
            (TerminalProfile::Codex, "/opt/bin/codex"),
            (TerminalProfile::Hermes, "/opt/my tools/hermes"),
        ]
        .into_iter()
        .map(|(profile, path)| CodingAgent {
            profile,
            command: path.rsplit('/').next().unwrap().to_owned(),
            path: path.to_owned(),
        })
        .collect()
    }

    fn bots_dir() -> PathBuf {
        std::env::temp_dir().join(format!("hh bots {}", Uuid::new_v4()))
    }

    fn spec(agent: TerminalProfile, home: Option<&Path>) -> BotSpec {
        BotSpec {
            pinned_threads: Vec::new(),
            thread_panes: std::collections::BTreeMap::default(),
            agent,
            instructions: Some("Prefer small PRs.".to_owned()),
            home: home.map(|home| home.to_str().unwrap().to_owned()),
        }
    }

    fn prepare(spec: &BotSpec, bots_dir: &Path, hh_cli: Option<&Path>) -> Result<PreparedLaunch> {
        let bot = BotLaunch {
            bot_id: Uuid::nil(),
            name: "Hive3",
            project_dir: Some("/srv/app"),
            spec,
            resume: None,
        };
        prepare_launch(&bot, &agents(), bots_dir, hh_cli)
    }

    fn command_for(agent: TerminalProfile, bots_dir: &Path, hh_cli: Option<&Path>) -> String {
        prepare(&spec(agent, None), bots_dir, hh_cli)
            .unwrap()
            .command
    }

    fn home(bots_dir: &Path) -> PathBuf {
        bots_dir.join(Uuid::nil().to_string())
    }

    #[test]
    fn omp_loads_the_extension_and_keeps_its_threads_in_the_bot_folder() {
        use std::os::unix::fs::PermissionsExt as _;
        let directory = bots_dir();
        let command = command_for(TerminalProfile::Omp, &directory, None);
        let extension = directory.join(OMP_EXTENSION_FILE);
        let threads = home(&directory).join("threads");
        assert_eq!(
            command,
            format!(
                "/opt/bin/omp -e '{}' --session-dir '{}'",
                extension.display(),
                threads.display()
            )
        );
        assert_eq!(fs::read(&extension).unwrap(), OMP_EXTENSION);
        assert_eq!(
            fs::metadata(&threads).unwrap().permissions().mode() & 0o777,
            0o700
        );

        let custom = bots_dir();
        fs::create_dir_all(&custom).unwrap();
        let spec = spec(TerminalProfile::Omp, Some(&custom));
        let bot = BotLaunch {
            bot_id: Uuid::nil(),
            name: "Hive3",
            project_dir: None,
            spec: &spec,
            resume: Some("0193-abc"),
        };
        let launch = prepare_launch(&bot, &agents(), &directory, None).unwrap();
        assert_eq!(
            launch.home, custom,
            "the shell still starts in the custom home"
        );
        assert_eq!(
            launch.command,
            format!(
                "/opt/bin/omp -e '{}' --session-dir '{}' --resume 0193-abc",
                extension.display(),
                threads.display()
            ),
            "threads stay in the HH-owned bot folder"
        );
        let bot = BotLaunch {
            resume: Some("x; rm -rf /"),
            ..bot
        };
        assert!(prepare_launch(&bot, &agents(), &directory, None).is_err());
        remove_bot_files(&directory, Uuid::nil());
        assert!(!threads.exists(), "deleting the bot deletes its threads");
        fs::remove_dir_all(custom).unwrap();
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn claude_gets_only_the_harness_harlot_mcp_server() {
        let directory = bots_dir();
        let hh = Path::new("/Applications/Harness Harlot.app/Contents/MacOS/hh");
        let command = command_for(TerminalProfile::Claude, &directory, Some(hh));
        let config = directory.join(format!("{}.mcp.json", Uuid::nil()));
        assert_eq!(
            command,
            format!("/opt/bin/claude --mcp-config '{}'", config.display())
        );
        let config: serde_json::Value = serde_json::from_slice(&fs::read(config).unwrap()).unwrap();
        assert_eq!(
            config,
            serde_json::json!({
                "mcpServers": {"harness-harlot": {"command": hh.to_str().unwrap(), "args": ["mcp"]}}
            })
        );
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn codex_gets_only_the_harness_harlot_mcp_server() {
        let directory = bots_dir();
        let command = command_for(
            TerminalProfile::Codex,
            &directory,
            Some(Path::new("/opt/hh")),
        );
        assert_eq!(
            command,
            "/opt/bin/codex -c 'mcp_servers.harness-harlot.command=\"/opt/hh\"' -c 'mcp_servers.harness-harlot.args=[\"mcp\"]'"
        );
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn every_agent_gets_an_owner_only_agents_md_in_its_default_home() {
        use std::os::unix::fs::PermissionsExt as _;
        for agent in [
            TerminalProfile::Omp,
            TerminalProfile::Claude,
            TerminalProfile::Codex,
            TerminalProfile::Hermes,
        ] {
            let directory = bots_dir();
            let launch =
                prepare(&spec(agent, None), &directory, Some(Path::new("/opt/hh"))).unwrap();
            if agent == TerminalProfile::Hermes {
                assert_eq!(launch.command, "'/opt/my tools/hermes'");
            }
            assert_eq!(launch.home, home(&directory));
            assert!(launch.context_written);
            let mode = |path: &Path| fs::metadata(path).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode(&launch.home), 0o700);
            let context = launch.home.join(CONTEXT_FILE);
            assert_eq!(mode(&context), 0o600);
            let context = fs::read_to_string(context).unwrap();
            assert!(context.starts_with(&format!(
                "<!-- Generated by Harness Harlot for bot {}; rewritten on every launch. -->\n{}",
                Uuid::nil(),
                COORDINATOR_PROMPT.trim_end()
            )));
            assert!(context.contains("Your name is \"Hive3\""));
            assert!(
                context.contains(
                    "Your project folder: /srv/app. Workers you open go there by default."
                )
            );
            assert!(context.ends_with("Prefer small PRs.\n"));
            fs::remove_dir_all(directory).unwrap();
        }
    }

    #[test]
    fn agents_md_teaches_the_harness_harlot_cli() {
        let spec = BotSpec {
            pinned_threads: Vec::new(),
            thread_panes: std::collections::BTreeMap::default(),
            agent: TerminalProfile::Hermes,
            instructions: None,
            home: None,
        };
        let context = context_file(&BotLaunch {
            bot_id: Uuid::nil(),
            name: "Hive3",
            project_dir: None,
            spec: &spec,
            resume: None,
        });
        assert!(context.contains("the CLI at `$HH_CLI` (always set in your terminal)"));
        assert!(context.contains(
            "`\"$HH_CLI\" terminal new --title <name> [--cwd <dir>] [--command '<cmd>'] --json`"
        ));
        assert!(!context.contains("Your project folder"));
        assert!(!context.contains("Standing instructions"));
    }

    #[test]
    fn a_custom_home_keeps_the_users_own_agents_md_and_its_permissions() {
        use std::os::unix::fs::PermissionsExt as _;
        let directory = bots_dir();
        let custom = bots_dir();
        fs::create_dir_all(&custom).unwrap();
        fs::set_permissions(&custom, fs::Permissions::from_mode(0o755)).unwrap();
        let spec = spec(TerminalProfile::Hermes, Some(&custom));

        let launch = prepare(&spec, &directory, None).unwrap();
        assert_eq!(launch.home, custom);
        assert!(launch.context_written);
        assert!(!home(&directory).exists(), "no default home is created");
        let generated = fs::read_to_string(custom.join(CONTEXT_FILE)).unwrap();
        assert!(generated.starts_with(CONTEXT_MARKER));
        assert_eq!(
            fs::metadata(&custom).unwrap().permissions().mode() & 0o777,
            0o755
        );

        fs::write(custom.join(CONTEXT_FILE), generated.replace("Hive3", "Old")).unwrap();
        assert!(prepare(&spec, &directory, None).unwrap().context_written);
        assert_eq!(
            fs::read_to_string(custom.join(CONTEXT_FILE)).unwrap(),
            generated
        );

        let own = b"# Repo rules\nUse tabs.\n";
        fs::write(custom.join(CONTEXT_FILE), own).unwrap();
        let launch = prepare(&spec, &directory, None).unwrap();
        assert!(!launch.context_written);
        assert_eq!(fs::read(custom.join(CONTEXT_FILE)).unwrap(), own);

        remove_bot_files(&directory, Uuid::nil());
        assert_eq!(fs::read(custom.join(CONTEXT_FILE)).unwrap(), own);
        fs::remove_dir_all(custom).unwrap();
        let _ = fs::remove_dir_all(directory);
    }

    #[test]
    fn a_missing_custom_home_is_rejected() {
        let missing = bots_dir();
        let error = prepare(
            &spec(TerminalProfile::Hermes, Some(&missing)),
            &bots_dir(),
            None,
        )
        .err()
        .unwrap();
        assert_eq!(
            error.to_string(),
            format!(
                "bot home {} is not an existing directory",
                missing.display()
            )
        );
    }

    #[test]
    fn removing_bot_files_deletes_the_default_home_without_following_a_symlink() {
        let directory = bots_dir();
        command_for(
            TerminalProfile::Claude,
            &directory,
            Some(Path::new("/opt/hh")),
        );
        fs::write(home(&directory).join("notes.md"), "todo").unwrap();
        remove_bot_files(&directory, Uuid::nil());
        assert!(!home(&directory).exists());
        assert!(!directory.join(format!("{}.mcp.json", Uuid::nil())).exists());

        let target = bots_dir();
        fs::create_dir_all(&target).unwrap();
        fs::write(target.join("keep"), "keep").unwrap();
        std::os::unix::fs::symlink(&target, home(&directory)).unwrap();
        remove_bot_files(&directory, Uuid::nil());
        assert!(fs::symlink_metadata(home(&directory)).is_err());
        assert!(target.join("keep").is_file());
        fs::remove_dir_all(directory).unwrap();
        fs::remove_dir_all(target).unwrap();
    }

    #[test]
    fn missing_and_non_agent_profiles_are_rejected() {
        let error = prepare(&spec(TerminalProfile::Gemini, None), &bots_dir(), None)
            .err()
            .unwrap();
        assert_eq!(error.to_string(), "Gemini CLI is not installed");
        let error = prepare(&spec(TerminalProfile::Terminal, None), &bots_dir(), None)
            .err()
            .unwrap();
        assert_eq!(error.to_string(), "Terminal is not a coding agent");
    }

    #[test]
    fn shell_quoting_survives_single_quotes() {
        assert_eq!(shell_quote("/usr/bin/omp"), "/usr/bin/omp");
        assert_eq!(shell_quote("it's"), "'it'\\''s'");
        assert_eq!(shell_quote(""), "''");
    }
}
