use std::collections::{BTreeMap, BTreeSet};
use std::fmt;
use std::io;

use gpui::Keystroke;
use serde::{Deserialize, Serialize};

pub const ROOT_KEY_CONTEXT: &str = "NAHTerminal";

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum AppCommand {
    NewWorkspace,
    ToggleSidebar,
    NewTab,
    NewBrowserTab,
    TerminalZoomIn,
    TerminalZoomOut,
    SplitRight,
    SplitDown,
    FocusLeft,
    FocusRight,
    FocusUp,
    FocusDown,
    ShowCommandPalette,
    TogglePaneZoom,
    EqualizePanes,
    ReattachPane,
    ShowNotifications,
}

impl AppCommand {
    const COUNT: usize = 17;
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CommandDescriptor {
    pub command: AppCommand,
    /// Stable configuration and palette identifier. These are compatibility
    /// surface, unlike the Rust action type names generated by GPUI.
    pub id: &'static str,
    pub title: &'static str,
    pub category: &'static str,
    pub default_bindings: &'static [&'static str],
}

pub const COMMAND_DESCRIPTORS: &[CommandDescriptor] = &[
    CommandDescriptor {
        command: AppCommand::NewWorkspace,
        id: "workspace.new",
        title: "New Workstation",
        category: "Workstation",
        default_bindings: &["cmd-n"],
    },
    CommandDescriptor {
        command: AppCommand::ToggleSidebar,
        id: "workspace.toggle-sidebar",
        title: "Toggle Workstation Sidebar",
        category: "Workstation",
        default_bindings: &["cmd-b"],
    },
    CommandDescriptor {
        command: AppCommand::NewTab,
        id: "terminal.new-tab",
        title: "New Terminal Tab",
        category: "Terminal",
        default_bindings: &["cmd-t"],
    },
    CommandDescriptor {
        command: AppCommand::NewBrowserTab,
        id: "workspace.new-browser-tab",
        title: "New Browser Tab",
        category: "Workstation",
        default_bindings: &[],
    },
    CommandDescriptor {
        command: AppCommand::TerminalZoomIn,
        id: "terminal.zoom-in",
        title: "Increase Terminal Font Size",
        category: "Terminal",
        default_bindings: &["secondary-=", "secondary-shift-=", "secondary-+"],
    },
    CommandDescriptor {
        command: AppCommand::TerminalZoomOut,
        id: "terminal.zoom-out",
        title: "Decrease Terminal Font Size",
        category: "Terminal",
        default_bindings: &["secondary--"],
    },
    CommandDescriptor {
        command: AppCommand::SplitRight,
        id: "pane.split-right",
        title: "Split Pane Right",
        category: "Pane",
        default_bindings: &["cmd-d"],
    },
    CommandDescriptor {
        command: AppCommand::SplitDown,
        id: "pane.split-down",
        title: "Split Pane Down",
        category: "Pane",
        default_bindings: &["cmd-shift-d"],
    },
    CommandDescriptor {
        command: AppCommand::FocusLeft,
        id: "pane.focus-left",
        title: "Focus Pane Left",
        category: "Pane",
        default_bindings: &["cmd-alt-left"],
    },
    CommandDescriptor {
        command: AppCommand::FocusRight,
        id: "pane.focus-right",
        title: "Focus Pane Right",
        category: "Pane",
        default_bindings: &["cmd-alt-right"],
    },
    CommandDescriptor {
        command: AppCommand::FocusUp,
        id: "pane.focus-up",
        title: "Focus Pane Up",
        category: "Pane",
        default_bindings: &["cmd-alt-up"],
    },
    CommandDescriptor {
        command: AppCommand::FocusDown,
        id: "pane.focus-down",
        title: "Focus Pane Down",
        category: "Pane",
        default_bindings: &["cmd-alt-down"],
    },
    CommandDescriptor {
        command: AppCommand::ShowCommandPalette,
        id: "app.command-palette",
        title: "Show Command Palette",
        category: "Application",
        default_bindings: &["cmd-shift-p"],
    },
    CommandDescriptor {
        command: AppCommand::TogglePaneZoom,
        id: "pane.toggle-zoom",
        title: "Toggle Pane Zoom",
        category: "Pane",
        default_bindings: &["cmd-shift-enter"],
    },
    CommandDescriptor {
        command: AppCommand::EqualizePanes,
        id: "pane.equalize",
        title: "Equalize Pane Sizes",
        category: "Pane",
        default_bindings: &["cmd-alt-e"],
    },
    CommandDescriptor {
        command: AppCommand::ReattachPane,
        id: "pane.reattach",
        title: "Reattach Exited Terminal",
        category: "Pane",
        default_bindings: &["cmd-shift-r"],
    },
    CommandDescriptor {
        command: AppCommand::ShowNotifications,
        id: "app.session.notifications",
        title: "Show Notifications",
        category: "Application",
        default_bindings: &[],
    },
];

const fn str_eq(left: &str, right: &str) -> bool {
    let left = left.as_bytes();
    let right = right.as_bytes();
    if left.len() != right.len() {
        return false;
    }
    let mut index = 0;
    while index < left.len() {
        if left[index] != right[index] {
            return false;
        }
        index += 1;
    }
    true
}

const fn check_registry() {
    assert!(COMMAND_DESCRIPTORS.len() == AppCommand::COUNT);
    let mut outer = 0;
    while outer < COMMAND_DESCRIPTORS.len() {
        let descriptor = &COMMAND_DESCRIPTORS[outer];
        assert!(descriptor.command as usize == outer);
        assert!(!descriptor.id.is_empty());
        assert!(!descriptor.title.is_empty());
        assert!(
            !descriptor.default_bindings.is_empty()
                || matches!(
                    descriptor.command,
                    AppCommand::NewBrowserTab | AppCommand::ShowNotifications
                )
        );
        let mut inner = outer + 1;
        while inner < COMMAND_DESCRIPTORS.len() {
            let other = &COMMAND_DESCRIPTORS[inner];
            assert!(!str_eq(descriptor.id, other.id));
            assert!(descriptor.command as u8 != other.command as u8);
            inner += 1;
        }
        outer += 1;
    }
}

const _: () = check_registry();

pub fn descriptor(command: AppCommand) -> &'static CommandDescriptor {
    &COMMAND_DESCRIPTORS[command as usize]
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct AppConfig {
    /// Each entry replaces all defaults for the stable action ID. An empty
    /// array intentionally unbinds the action while leaving it in the palette.
    pub keybindings: BTreeMap<String, Vec<String>>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ResolvedBinding {
    pub command: AppCommand,
    pub sequence: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ResolvedKeymap {
    pub bindings: Vec<ResolvedBinding>,
    /// Synthetic bindings for incomplete chord prefixes prevent GPUI's normal
    /// timeout replay from writing the prefix into a PTY.
    pub chord_prefixes: Vec<String>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConfigError(String);

impl fmt::Display for ConfigError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl std::error::Error for ConfigError {}

impl AppConfig {
    pub fn from_json(json: &str) -> Result<Self, ConfigError> {
        serde_json::from_str(json)
            .map_err(|error| ConfigError(format!("invalid config JSON: {error}")))
    }

    pub fn load() -> Result<Self, ConfigError> {
        let Some(path) = hh_protocol::config_path() else {
            return Ok(Self::default());
        };
        let bytes = match hh_protocol::read_private_file(&path, 64 * 1024) {
            Ok(bytes) => bytes,
            Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(Self::default()),
            Err(error) => {
                return Err(ConfigError(format!("read {}: {error}", path.display())));
            }
        };
        let json = String::from_utf8(bytes)
            .map_err(|error| ConfigError(format!("{} is not UTF-8: {error}", path.display())))?;
        Self::from_json(&json).map_err(|error| ConfigError(format!("{}: {error}", path.display())))
    }

    pub fn resolve_keymap(&self) -> Result<ResolvedKeymap, ConfigError> {
        for id in self.keybindings.keys() {
            if !COMMAND_DESCRIPTORS
                .iter()
                .any(|descriptor| descriptor.id == id)
            {
                return Err(ConfigError(format!("unknown action ID `{id}`")));
            }
        }

        let mut bindings = Vec::new();
        let mut occupied = BTreeMap::<String, &'static str>::new();
        for descriptor in COMMAND_DESCRIPTORS {
            let configured = self.keybindings.get(descriptor.id);
            let sequences: Vec<&str> = configured.map_or_else(
                || descriptor.default_bindings.to_vec(),
                |configured| configured.iter().map(String::as_str).collect(),
            );
            let mut within_action = BTreeSet::new();
            for sequence in sequences {
                let sequence = normalize_sequence(sequence)?;
                if !within_action.insert(sequence.clone()) {
                    return Err(ConfigError(format!(
                        "action `{}` repeats binding `{sequence}`",
                        descriptor.id
                    )));
                }
                if let Some(existing) = occupied.insert(sequence.clone(), descriptor.id) {
                    return Err(ConfigError(format!(
                        "binding `{sequence}` is assigned to both `{existing}` and `{}`",
                        descriptor.id
                    )));
                }
                bindings.push(ResolvedBinding {
                    command: descriptor.command,
                    sequence,
                });
            }
        }

        let exact = bindings
            .iter()
            .map(|binding| binding.sequence.as_str())
            .collect::<BTreeSet<_>>();
        let mut chord_prefixes = BTreeSet::new();
        for binding in &bindings {
            let strokes = binding.sequence.split_whitespace().collect::<Vec<_>>();
            for length in 1..strokes.len() {
                let prefix = strokes[..length].join(" ");
                if !exact.contains(prefix.as_str()) {
                    chord_prefixes.insert(prefix);
                }
            }
        }

        Ok(ResolvedKeymap {
            bindings,
            chord_prefixes: chord_prefixes.into_iter().collect(),
        })
    }
}

fn normalize_sequence(sequence: &str) -> Result<String, ConfigError> {
    let sequence = sequence.split_whitespace().collect::<Vec<_>>().join(" ");
    if sequence.is_empty() {
        return Err(ConfigError(
            "key binding sequences cannot be blank".to_owned(),
        ));
    }
    for stroke in sequence.split_whitespace() {
        Keystroke::parse(stroke).map_err(|error| {
            ConfigError(format!(
                "invalid keystroke `{stroke}` in `{sequence}`: {error}"
            ))
        })?;
    }
    Ok(sequence)
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PaletteMatch {
    pub command: AppCommand,
    pub score: i32,
}

pub fn palette_matches(query: &str, limit: usize) -> Vec<PaletteMatch> {
    let query = query.trim();
    let mut matches = COMMAND_DESCRIPTORS
        .iter()
        .filter_map(|descriptor| {
            let score = if query.is_empty() {
                0
            } else {
                fuzzy_score(query, descriptor.title)
                    .or_else(|| fuzzy_score(query, descriptor.id))?
            };
            Some(PaletteMatch {
                command: descriptor.command,
                score,
            })
        })
        .collect::<Vec<_>>();
    if !query.is_empty() {
        matches.sort_by(|left, right| {
            right.score.cmp(&left.score).then_with(|| {
                descriptor(left.command)
                    .title
                    .cmp(descriptor(right.command).title)
            })
        });
    }
    matches.truncate(limit);
    matches
}

fn fuzzy_score(needle: &str, haystack: &str) -> Option<i32> {
    let needle = needle.to_lowercase();
    let haystack = haystack.to_lowercase();
    let mut needle_chars = needle.chars();
    let mut wanted = needle_chars.next()?;
    let mut score = 0;
    let mut previous_match = None;
    for (index, candidate) in haystack.char_indices() {
        if candidate != wanted {
            continue;
        }
        score += 10;
        if previous_match.is_some_and(|previous| index == previous + 1) {
            score += 8;
        }
        if index == 0
            || haystack[..index]
                .chars()
                .next_back()
                .is_some_and(|previous| !previous.is_alphanumeric())
        {
            score += 6;
        }
        score -= i32::try_from(index).unwrap_or(i32::MAX) / 8;
        previous_match = Some(index);
        let Some(next) = needle_chars.next() else {
            if needle == haystack {
                score += 20;
            }
            return Some(score);
        };
        wanted = next;
    }
    None
}

#[cfg(test)]
mod tests {
    use super::{
        AppCommand, AppConfig, COMMAND_DESCRIPTORS, Keystroke, check_registry, descriptor,
        palette_matches,
    };

    #[test]
    fn registry_is_complete_unique_and_stably_addressable() {
        check_registry();
        for (index, entry) in COMMAND_DESCRIPTORS.iter().enumerate() {
            assert_eq!(descriptor(entry.command), entry);
            assert_eq!(entry.command as usize, index);
        }
        assert_eq!(
            descriptor(AppCommand::TogglePaneZoom).id,
            "pane.toggle-zoom"
        );
        assert_eq!(
            descriptor(AppCommand::ToggleSidebar).id,
            "workspace.toggle-sidebar"
        );
        assert_eq!(
            descriptor(AppCommand::ToggleSidebar).default_bindings,
            &["cmd-b"]
        );
    }

    #[test]
    fn serde_json_remaps_replace_defaults_and_empty_arrays_unbind() {
        let config = AppConfig::from_json(
            r#"{
                "keybindings": {
                    "pane.split-right": ["ctrl-b |"],
                    "pane.split-down": []
                }
            }"#,
        )
        .unwrap();
        let keymap = config.resolve_keymap().unwrap();

        assert!(keymap.bindings.iter().any(|binding| {
            binding.command == AppCommand::SplitRight && binding.sequence == "ctrl-b |"
        }));
        assert!(!keymap.bindings.iter().any(|binding| {
            binding.command == AppCommand::SplitRight && binding.sequence == "cmd-d"
        }));
        assert!(
            !keymap
                .bindings
                .iter()
                .any(|binding| binding.command == AppCommand::SplitDown)
        );
        assert_eq!(keymap.chord_prefixes, vec!["ctrl-b"]);
        assert_eq!(
            serde_json::from_str::<AppConfig>(&serde_json::to_string(&config).unwrap()).unwrap(),
            config
        );
    }

    #[test]
    fn remaps_reject_unknown_actions_invalid_keys_and_collisions() {
        let unknown =
            AppConfig::from_json(r#"{"keybindings":{"pane.teleport":["cmd-j"]}}"#).unwrap();
        assert!(
            unknown
                .resolve_keymap()
                .unwrap_err()
                .to_string()
                .contains("unknown action ID")
        );

        let invalid =
            AppConfig::from_json(r#"{"keybindings":{"pane.equalize":["foo-bar"]}}"#).unwrap();
        assert!(
            invalid
                .resolve_keymap()
                .unwrap_err()
                .to_string()
                .contains("invalid keystroke")
        );

        let collision =
            AppConfig::from_json(r#"{"keybindings":{"pane.equalize":["cmd-t"]}}"#).unwrap();
        assert!(
            collision
                .resolve_keymap()
                .unwrap_err()
                .to_string()
                .contains("assigned to both")
        );
    }

    #[test]
    fn every_incomplete_chord_prefix_gets_a_non_leaking_binding() {
        let config =
            AppConfig::from_json(r#"{"keybindings":{"pane.equalize":["ctrl-b p e"]}}"#).unwrap();
        let keymap = config.resolve_keymap().unwrap();
        assert_eq!(keymap.chord_prefixes, vec!["ctrl-b", "ctrl-b p"]);
    }

    #[test]
    fn palette_fuzzy_matching_prefers_tight_titles_and_accepts_stable_ids() {
        let matches = palette_matches("", usize::MAX);
        assert_eq!(matches.len(), COMMAND_DESCRIPTORS.len());
        assert_eq!(matches[0].command, AppCommand::NewWorkspace);
        assert_eq!(matches[14].command, AppCommand::EqualizePanes);

        let matches = palette_matches("eq pane", 8);
        assert_eq!(
            matches.first().map(|item| item.command),
            Some(AppCommand::EqualizePanes)
        );

        let matches = palette_matches("togglezoom", 8);
        assert_eq!(
            matches.first().map(|item| item.command),
            Some(AppCommand::TogglePaneZoom)
        );

        let matches = palette_matches("workspace.new", 8);
        assert_eq!(
            matches.first().map(|item| item.command),
            Some(AppCommand::NewWorkspace)
        );
    }

    #[test]
    fn terminal_zoom_bindings_cover_character_and_physical_plus_keys() {
        assert_eq!(
            descriptor(AppCommand::TerminalZoomIn).default_bindings,
            &["secondary-=", "secondary-shift-=", "secondary-+"]
        );
        assert_eq!(
            descriptor(AppCommand::TerminalZoomOut).default_bindings,
            &["secondary--"]
        );

        #[cfg(not(target_os = "windows"))]
        {
            let mut physical = Keystroke::parse("secondary-shift-=").unwrap();
            physical.key_char = Some("+".to_owned());
            let character =
                gpui::KeybindingKeystroke::from_keystroke(Keystroke::parse("secondary-+").unwrap());
            assert!(physical.should_match(&character));
        }
    }
}
