[package]
name = "hh-terminal-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Terminal model adapter for Harness Harlot"

[dependencies]
alacritty_terminal.workspace = true
hh-protocol = { version = "0.1.0", path = "../protocol" }

[lints]
workspace = true
