set -g default-terminal xterm-256color
set -g default-size 100x30
set -g history-limit 20000
set -g escape-time 0
set -g status off
set -g prefix None
set -g prefix2 None
set -g mouse off
set -g set-clipboard on
set -g allow-passthrough on
set -g focus-events on
set -g remain-on-exit off
set -g exit-empty on
set -g detach-on-destroy off
